name: Tagpr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tagpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: go install github.com/snaka/tagpr/cmd/tagpr@debug-20240919-1613
      - run: tagpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}