name: Test and Lint

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test -v ./...

    - name: Run golint
      run: go install golang.org/x/lint/golint@latest && golint ./...

    - name: Run go vet
      run: go vet ./...
